#include <bits/stdc++.h>

#define iQqlHCizytXZYKnAiIeGrkElmknSeXWHwfMAFuPpKPMJiZMdxvtVmZpsLyTFaREacTzyItxUTRNyjqPEXVyionLZPJiwreyVYgxT using
#define ByQzWjKYUfDOnAfBnYiMklRcqOhEfbpIyMaQbGFRaMqjsZDaZndyjHbZnqCelKyGvPmanurwOVdllUHOOalvYbBDGeYHyWLFUPLe namespace
#define nxpPnfQgMhcfBLXvkpFKbvQIGkeOgqlmwqpfNdFlhxHJnvdDIdflAWpgUSfmGsPpluNUXWYYdtNeJBqCSsXPJKRpiHedtqeWQskD std
#define VzRDtBteldPPBhFGGuQSAyHQYCWflMnxkAEvPgsIvTPAuTcAghesUoVgbUubggWwMCLEpizkNYknrJQQPvRzziHgifCDxwzpEtiE int
#define YOnsEJznvujApYJZrromuDGcoEOEotFfxGBsswBuQAExNfRLFRMmSsLwfgRvGdxuYZKFQPiRgWnGXspkqJuWOSquNRQnxCdPuYBM main
#define NpMXuhQkOgymWDSIkTuoNwNAbOtKctrEYmDxjemIckNOPevVdbDlsTGQexVaRfnKKRAkIKGINUwKtkXssTQwYMKLvAsZPcKvNsDz ios_base
#define cEaFeqrfXNjfQHlrZyQIxDThoEAIVFKyXDOzqmenLekQkOMXFbRpbYOtmtoVlXbJkhwDiWyTLqvcsaZHNfSPLbXfsPMXrSBiqgUM sync_with_stdio
#define kdWApgqJqymKvTbjYJVUtECEFidgEdXUwZqAtbRoxSzMRdiAVkWqJSBwKgRbQHOwvfEYVLfFNWvwsYrXYQRMJyLEQFPokTTsBLHL 0
#define TIAUcxqEbLfXmVkiZzhZiPMuYvHHghOOkIisGfOHuSTlqStTCDcIZcGuOLZWSHiNMtUFkgbFfGWbDlNPSdnzEDMqpIlhtVfYciCh cin
#define HVTSuLIpULXGffJHkpBMGUDAOPrXNdAVYRhuXXTygTskKvNdSugkqsCxmteRPqGQCxbWdIuiwxOtSjoIGanoUdziMIGWWYUbJDUE tie
#define kLIBNhTOqhsYtUEjjIdNnVwtQOOROhuwFFFhcMzyHiOTJMYTAblXjSrjbgSpnLhHCxTgaefsanNEjhOtUnkGUBoEoZBTxgxmUKeR cout
#define gpTkMIAIYiBLMPJPktmlaGHCEfGvCCzLaYpCrCrLMUXyGesRCRxAeSPdBrlKajGrSnLmtSNmCFJkOXwjJKFdhitrnqdYDnScijci freopen
#define npeKFlkoTZCDKAYEGydGBDBVMxKUyXiLvsZPkHujxTVxDfGDinGNZBeUxRYkjkAEmYVMKoXjEziOWODKRjeiZsSBdZOnkrJUbyNX stdin
#define mrlfHdrgJCEVCXGjuJDkVKzEuWOPHqxgjVcGhNCGQxegMkVBhBFEYBVaspYgwRYxRYYunOgnbdZnsVHKMfRTNFEyDwSNWDbdIpBN stdout
#define zyaRynomEoRwJVSGStcmwGGJEvGMglnhikPuAEktKHtHwntVhFifsffEgGkeqTlAXHENSFCfvTFheSyQxkLvXFhAqQtNyyCqryrm n
#define JZwIpOQEqMZYANqltQZKZetNiuOwSfcZpVUmXbyHXwJjuygUFMDgZWiTIAxThnrVBguUfTsgRASGhqJxbCKeojPdkVDJhvCaVqtx m
#define flmKDJaBLOWTjlrEMCzKJtptjcXwUjXZDVxHupWWOfOJdJVifTZwOUXVnFqQdSqDalzHNsbxskUrgEzWPJapNLnBvFJrPXIOjScn 9
#define dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD ;
#define lfCFOyrjENoeSoyuHagWdTYCcFjcrjEXsBIOxSjDoENuulMsiiWhtsDqmhcVGTNujQkCEppHxbCnrbaQaSusqxKUjRMwHbVgRXdL {
#define XynqgvhOyfKdSmgsfEoxGarucvvEnWxbFSaFpjyFNWDgKBQHnZWFllmzgqrXKdmZNKpzOGDSQZRokviNEGmbtAYZoanBtAmoMzdV }
#define CTeMYRCwfQGIMhxBLdJCWQKxzYVAgdINGJhJEXVgmuJvjseJiXGSESCMNeLMTEdkngjQDuZZkqIBVBKCJsZQwxLLTOQajxcIWYJc /=
#define XmgGAmhZBcedWgXPLyuoUJyQPIDvhpgGMPWjBjmiYJhbfmtWSteUWGqUgfTDDecDqruMSyOrNgLwYCrfoZtJmEjXntbAjtMyVtRB +=
#define setkZtVnxCHBeLaxwiinWHvQoIBOkjkSiXqiYOJEZGycEmtTGdkyMlBQhMxeWmsxYVJyXAKmHGJxWavOSjqBTKtACeLyLVQwwQwv -=
#define JkVnTMbgKjYZGSkRJnxhfMRFiogInRVkkwPXFPfSapNmKmfSGcwlWvguzPbzyuwLgDcDGrtLqsjSlsuaarYjYlGnarvuEYWhkwRb *=
#define LGnckPEgDBjtCdEwyKdmqEPlBljACnbNumOhSDOKZSaoxoEMJJqaPDQpZWlcPUrYMFwxznhqUmowSTOMggIZzpXHchtCyxYCsvdL !=
#define dqXXUlUkDggUTOaUcXdPXqIlcOuDdJsABgySoXvkQBGOBrkTIihZcSAcLHqLLyHTOAmJuHHCnjqHYFXwgmNazspOGKZPuhuVLbDO %=
#define edjjADpoVdqTZzlqHasqhfgrKDDiXmlgnwbWfNsSaTeqBXjyTVbKyukGZeJuORdvtezrQkWQcFqXaVhnZeNHkIAGqToajRHamZQY ^=
#define jcPmixHvZusVkYipvONsTNZbLiyONaNxhrhBeXOClYdjyGHMbNkgNHzTmGEqjOhBIHLpXzUGEFvfZjgqAQqiokLVADzWJCOGNLXG |=
#define ckNreNDhiClOkbeWOyvhYPpPYgUKqDOAlEnyNchAgcwfJRLerLKpTncnNOwkBGvMEBwyPkmCRvinYQSzuNBxdTPgCiPeNiiKENvn &=
#define enyvKxWUaesimERdzempVadcLnidEfPnKDtvqCYsscOkIUjwrYhHbWIfWPIhPPXccHGhydTRaZlkcYDLSsfaPBtjzFOAfPWzilbF ||
#define xNDvVKHbvzxzLhesKKSaZODwDLphPzHQjaiRoCYGxmprCZZRiTvuhkTCDgNnYHYfhyGaPzPTXwuONBXNyBKZmTTahtoveHkfjonK &&
#define migcBvUiLrmDiwrOaeOkMBQJjKLuhFMYVNEGOOPQaZhhHlGAwNUcfuiHkJjHQGfLkCMPondfiirEIcNVUVIcrXqXleCmIZpTHSoX *
#define fTpWRipicjbDaZrMhKUeScoSFgMnegGiIjpHWOFbrcBATvnYIsjMmZdpzIZhWrzpdLoxFafRtASAAZNXSLvbzMjiTBoCwaUuuxxl /
#define nnWIfFLfaCkwJBEDlluxpwBbHExvlbgceXgDuhfLaJhOPIXbNgpcMeDznTZxPBaopiAOzJURipZQwzNHrYvHRbIrMwBpiWWBZBML ++
#define tYsLLDCMEyugCEpLRCFUjMDILFLsUJtSLzExrbuEpMEjjJqeMqbOsiBNsGOjZmBDmCyWnbITXfQhLPhBgTTZyTZMOrZozAlatXXx --
#define WVfrnpjDKvaAEOcMBmnKpoIQhDqgfchhXhIlIJUjFlODgFnZDjWMFCzmTflnpTswKOOVXXtPsTTCiAEhYUWrCFVIchiQrWjPDEeb +
#define KbTXissWghCqwypdAvXOWuhkiENzhCqyeMkKAeeXQaCdjawVDKkJsUybqtCtJFdBTSyhmACeigemYuOKQCdNuaYXwBHzYkAZMQoS -
#define paFhyyOLPkdDsOeAktoeveWCFoHLbOJQtCOYrDQtUquURcSigbcmCNHweNSVOHQpGXPMpiVdCaplaBJImeOzPYeRXGqbJRxIwQVa %
#define ZPHUcSVYvUgwJVMvkouATMbvobIsjZYuAbNutmtWSZZAnztCjFxfRwbpTinvnQLDFCHhGALmKglOAnnviRQaLCbPGwNRKYuByeHt ^
#define zBlQVniTLrzaWqZBuOiVlycSjRateeWWmdXXQpQRMQeBnohtiZHfKurjsowqVJjUZKcOFotOcFnBckpsNTNgnpiNdRBtbEAvRLSY ?
#define xYelbZVpEBoaBRcZIskFXEPBOPNEOMJbLeYKCjHKemUTGqTfEUfmRBOLFAAzsiSZQTPzzuEoEaahJHhqBoNEBEmaecGpjIOqhCgD &
#define mHDPudBzVoqcuKTjiQYvCUBRSWwGuDQjBZfxRXRFWGisNGEZJzbUeoIvbwnxboVxgbpuRIslqKENptBvTsmkLPQrJrKTLuINnUer |
#define xIIuZkAWfNwtGBRIJWfwxbRptBSWBYXfWJhkyVyPWkgvUCSWaFWRAuLrwRaDgBFFYlPkCvJhmEQGLsqrDLdJerlJJDGhPrnAJxfm !
#define cBKgpAhqhgIcexKUsdkEhibYddQbpaelOkjHlnZLNRVdJrGGmXNFYRSrlEoRKekXsWJTmcoJPciZjEZiabqFAYUBNkTgbufDZMsB ==
#define kvbQgFAGIMwfpliANHxhOAacWierKPGFUpYBWoFudHKYzzHPGbHLVcVtRAbtazSjotwXWouMcRgKBExLhGSMarcjFtdkettwMzMf >>
#define mfNTmueEZGShgHurTJgZTpncPtiKfyXEPhSuWryzhQQFfngUxDLUYdUymJNELOxNPLgowAGhnxtfMcyXVpnSrYVLMppuWKQISbwK <<
#define ShdLGiALtIIZGgRcasxjjetiDcyejzIzixiyGRlPPrzNmqbjKqdlyakdcOcVQQSbkxZalipLrdAbPzRrzNxYjgxMPpZjyNVgInYA <=
#define kziqLciDQHeIaNgkWPCZjBQmGMvnpKctiKgMWPdoXGvvcieamHURUPhrCmMIlKRHIosWOTNWyuIzoEZmzeBLLUOrbmYsrOYTOWSh >=
#define cyQMNXrMoolScbiwQVGyEiVkUKxpKUjBCbaDWEvFFCFigoEVlFqCVvtKFvLpkDepmvguUUSDmuNhsHpfZgrADpRyHqSxzhxFRCSZ ->
#define DXmeMKWNVFugrczoEHAdoxJGnvwlEtUsidzWrfVAVHkLiRThEGAZVifJPVxOsLliZyAhtcKSVUOFvpGoOpiLBjksPCLYKorgiGGX =
#define rMSABuhRLtBIXbXqJSnNALKwyxpxyFbmnaqjXvfNywyPlRZUUccKBYrwszBbjzACEArAswMfzYhDeEmNtKUqmcIcnvsrSgeLgRIG <
#define STnSXAsIjDWiqGlJqNIZKBMMZNyDeDfIsyWyCncmEyQPZFGwfUDdmTuiRkHKOSxOYguyNOknczVNbBpjwkhwlnVvzVVeUMrDrJxJ >


iQqlHCizytXZYKnAiIeGrkElmknSeXWHwfMAFuPpKPMJiZMdxvtVmZpsLyTFaREacTzyItxUTRNyjqPEXVyionLZPJiwreyVYgxT ByQzWjKYUfDOnAfBnYiMklRcqOhEfbpIyMaQbGFRaMqjsZDaZndyjHbZnqCelKyGvPmanurwOVdllUHOOalvYbBDGeYHyWLFUPLe nxpPnfQgMhcfBLXvkpFKbvQIGkeOgqlmwqpfNdFlhxHJnvdDIdflAWpgUSfmGsPpluNUXWYYdtNeJBqCSsXPJKRpiHedtqeWQskD dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
VzRDtBteldPPBhFGGuQSAyHQYCWflMnxkAEvPgsIvTPAuTcAghesUoVgbUubggWwMCLEpizkNYknrJQQPvRzziHgifCDxwzpEtiE YOnsEJznvujApYJZrromuDGcoEOEotFfxGBsswBuQAExNfRLFRMmSsLwfgRvGdxuYZKFQPiRgWnGXspkqJuWOSquNRQnxCdPuYBM()
 lfCFOyrjENoeSoyuHagWdTYCcFjcrjEXsBIOxSjDoENuulMsiiWhtsDqmhcVGTNujQkCEppHxbCnrbaQaSusqxKUjRMwHbVgRXdL 
 NpMXuhQkOgymWDSIkTuoNwNAbOtKctrEYmDxjemIckNOPevVdbDlsTGQexVaRfnKKRAkIKGINUwKtkXssTQwYMKLvAsZPcKvNsDz::cEaFeqrfXNjfQHlrZyQIxDThoEAIVFKyXDOzqmenLekQkOMXFbRpbYOtmtoVlXbJkhwDiWyTLqvcsaZHNfSPLbXfsPMXrSBiqgUM(kdWApgqJqymKvTbjYJVUtECEFidgEdXUwZqAtbRoxSzMRdiAVkWqJSBwKgRbQHOwvfEYVLfFNWvwsYrXYQRMJyLEQFPokTTsBLHL) dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 TIAUcxqEbLfXmVkiZzhZiPMuYvHHghOOkIisGfOHuSTlqStTCDcIZcGuOLZWSHiNMtUFkgbFfGWbDlNPSdnzEDMqpIlhtVfYciCh.HVTSuLIpULXGffJHkpBMGUDAOPrXNdAVYRhuXXTygTskKvNdSugkqsCxmteRPqGQCxbWdIuiwxOtSjoIGanoUdziMIGWWYUbJDUE(kdWApgqJqymKvTbjYJVUtECEFidgEdXUwZqAtbRoxSzMRdiAVkWqJSBwKgRbQHOwvfEYVLfFNWvwsYrXYQRMJyLEQFPokTTsBLHL) dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 kLIBNhTOqhsYtUEjjIdNnVwtQOOROhuwFFFhcMzyHiOTJMYTAblXjSrjbgSpnLhHCxTgaefsanNEjhOtUnkGUBoEoZBTxgxmUKeR.HVTSuLIpULXGffJHkpBMGUDAOPrXNdAVYRhuXXTygTskKvNdSugkqsCxmteRPqGQCxbWdIuiwxOtSjoIGanoUdziMIGWWYUbJDUE(kdWApgqJqymKvTbjYJVUtECEFidgEdXUwZqAtbRoxSzMRdiAVkWqJSBwKgRbQHOwvfEYVLfFNWvwsYrXYQRMJyLEQFPokTTsBLHL) dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 gpTkMIAIYiBLMPJPktmlaGHCEfGvCCzLaYpCrCrLMUXyGesRCRxAeSPdBrlKajGrSnLmtSNmCFJkOXwjJKFdhitrnqdYDnScijci("MARKET.INP", "r", npeKFlkoTZCDKAYEGydGBDBVMxKUyXiLvsZPkHujxTVxDfGDinGNZBeUxRYkjkAEmYVMKoXjEziOWODKRjeiZsSBdZOnkrJUbyNX) dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 gpTkMIAIYiBLMPJPktmlaGHCEfGvCCzLaYpCrCrLMUXyGesRCRxAeSPdBrlKajGrSnLmtSNmCFJkOXwjJKFdhitrnqdYDnScijci("MARKET.OUT", "w", mrlfHdrgJCEVCXGjuJDkVKzEuWOPHqxgjVcGhNCGQxegMkVBhBFEYBVaspYgwRYxRYYunOgnbdZnsVHKMfRTNFEyDwSNWDbdIpBN) dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 VzRDtBteldPPBhFGGuQSAyHQYCWflMnxkAEvPgsIvTPAuTcAghesUoVgbUubggWwMCLEpizkNYknrJQQPvRzziHgifCDxwzpEtiE zyaRynomEoRwJVSGStcmwGGJEvGMglnhikPuAEktKHtHwntVhFifsffEgGkeqTlAXHENSFCfvTFheSyQxkLvXFhAqQtNyyCqryrm dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 TIAUcxqEbLfXmVkiZzhZiPMuYvHHghOOkIisGfOHuSTlqStTCDcIZcGuOLZWSHiNMtUFkgbFfGWbDlNPSdnzEDMqpIlhtVfYciCh kvbQgFAGIMwfpliANHxhOAacWierKPGFUpYBWoFudHKYzzHPGbHLVcVtRAbtazSjotwXWouMcRgKBExLhGSMarcjFtdkettwMzMf zyaRynomEoRwJVSGStcmwGGJEvGMglnhikPuAEktKHtHwntVhFifsffEgGkeqTlAXHENSFCfvTFheSyQxkLvXFhAqQtNyyCqryrm dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 VzRDtBteldPPBhFGGuQSAyHQYCWflMnxkAEvPgsIvTPAuTcAghesUoVgbUubggWwMCLEpizkNYknrJQQPvRzziHgifCDxwzpEtiE JZwIpOQEqMZYANqltQZKZetNiuOwSfcZpVUmXbyHXwJjuygUFMDgZWiTIAxThnrVBguUfTsgRASGhqJxbCKeojPdkVDJhvCaVqtx dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 TIAUcxqEbLfXmVkiZzhZiPMuYvHHghOOkIisGfOHuSTlqStTCDcIZcGuOLZWSHiNMtUFkgbFfGWbDlNPSdnzEDMqpIlhtVfYciCh kvbQgFAGIMwfpliANHxhOAacWierKPGFUpYBWoFudHKYzzHPGbHLVcVtRAbtazSjotwXWouMcRgKBExLhGSMarcjFtdkettwMzMf JZwIpOQEqMZYANqltQZKZetNiuOwSfcZpVUmXbyHXwJjuygUFMDgZWiTIAxThnrVBguUfTsgRASGhqJxbCKeojPdkVDJhvCaVqtx dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 kLIBNhTOqhsYtUEjjIdNnVwtQOOROhuwFFFhcMzyHiOTJMYTAblXjSrjbgSpnLhHCxTgaefsanNEjhOtUnkGUBoEoZBTxgxmUKeR mfNTmueEZGShgHurTJgZTpncPtiKfyXEPhSuWryzhQQFfngUxDLUYdUymJNELOxNPLgowAGhnxtfMcyXVpnSrYVLMppuWKQISbwK flmKDJaBLOWTjlrEMCzKJtptjcXwUjXZDVxHupWWOfOJdJVifTZwOUXVnFqQdSqDalzHNsbxskUrgEzWPJapNLnBvFJrPXIOjScn dlrGVWjjHTPlhrASqOCKPaUWnxwDkUnwzmsbySzdZrrQaAWgRmQDRXulBRqbzrdNkEvEgnkGqCXwJCYYMboPxJUwyXmQgwdENavD 
 XynqgvhOyfKdSmgsfEoxGarucvvEnWxbFSaFpjyFNWDgKBQHnZWFllmzgqrXKdmZNKpzOGDSQZRokviNEGmbtAYZoanBtAmoMzdV 